print("In welke straat woon je?")
straatnaam = input()
print("Wat is het huisnummer?")
huisnummer = input()
print("In welke plaats is dat?")
woonplaats = input()
print("Wat is je postcode?")
postcode = input()
print("Dan is je adres dus:")
print(straatnaam,huisnummer)
print(postcode,woonplaats)